#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# System-wide files"
echo "Now installing system-wide files"
cd keyboard
find keymaps/ -type f -exec sudo install -Dm 644 "{}" "/usr/share/X11/xkb/{}" \;
cd ..
find etc/ -type f -exec sudo install -m 644 "{}" "/etc/" \;
find usr/bin/ -type f -exec sudo install -m 755 "{}" "/usr/bin/" \;
