#!/bin/bash

# Use sh to make sxhkd react faster because fish is slow...
export SXHKD_SHELL='/usr/bin/sh'

# /!\ The following seems to introduce a little bug while run in user's session: the main part of the keyboard won't use the correct layout until until a key from the second part is used!
# # Use the belgian keyboard layout by default, in case the next customizations don't work or the use of another (and more classic) keyboard.
# setxkbmap be
#
# # Check if the custom keymaps for the ZBoard are there and if so, use them.
# test -f /home/vrakfall/.keymaps/xorg/zboard-merc-part1-normal.xkb && xkbcomp -i 11 ~/.keymaps/xorg/zboard-merc-part1-normal.xkb $DISPLAY
# test -f /home/vrakfall/.keymaps/xorg/zboard-merc-part2-normal-no-caps-lock.xkb && xkbcomp -i 12 ~/.keymaps/xorg/zboard-merc-part2-normal-no-caps-lock.xkb $DISPLAY

# Get the first HDMI display
export DISPLAY_HDMI0=$(xrandr -q | sed -n 's/\(^HDMI-[0-9]\(-[0-9]\)\?\) connected.*/\1/p')
# Get the first DVI display
export DISPLAY_DVI0=$(xrandr -q | sed -n 's/\(^DVI-I\(-[0-9]\)\?\) connected.*/\1/p')
